export var dataSoal = [
    {id:1, 
    soal: '1. Apa yang dimaksud dengan fotosintesis?', 
    url:'', 
    alt:'', 
    jawaban: ['a) Proses pembentukan oksigen dari karbon dioksida dan air menggunakan energi cahaya matahari',
'b) Proses pembentukan karbon dioksida dari oksigen menggunakan energi cahaya matahari',
'c) Proses pembentukan glukosa dari oksigen dan air menggunakan energi cahaya matahari.',
'd) Proses pembentukan air dari glukosa menggunakan energi cahaya matahari.'],
    keyjawaban:'a',
selectedJawaban:''},

    {id:2, 
    soal: '2. Berapakah gaya yang diperlukan untuk menggerakkan benda berbobot 10 kg dengan percepatan 5 m/s^2?', 
    url:'', 
    alt:'', 
    jawaban: ['a) 2 N','b) 5 N','c) 10 N', 'd) 50 N'],
    keyjawaban:'c',
    selectedJawaban:''},

    {id:3, 
    soal: '3. Apakah rumus kimia untuk air?', 
    url:'', 
    alt:'',
    jawaban: ['a) H2O','b) CO2','c) CH4', 'd) HCl'], 
    keyjawaban:'a',
    selectedJawaban:''},

    {id:4, 
    soal: '4. Apa yang menyebabkan musim panas dan musim dingin di Bumi?', 
    url:'', 
    alt:'', 
    jawaban: ['a) Rotasi Bumi pada sumbunya.',
'b) Revolusi Bumi mengelilingi Matahari.',
'c) Perubahan aktivitas Matahari.',
'd) Perubahan orbit Bumi.'],
    keyjawaban:'b',
    selectedJawaban:''},

    {id:5, 
    soal: '5. Apa yang dimaksud dengan pola aliran sungai dendritik?', 
    url:'', 
    alt:'', 
    jawaban: ['a) Pola aliran sungai yang menyerupai pohon.',
'b) Pola aliran sungai yang menyerupai garis lurus.',
'c) Pola aliran sungai yang menyerupai jala.',
'd) Pola aliran sungai yang menyerupai segitiga.'],
    keyjawaban:'a',
    selectedJawaban:''},
]